name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Клонирование репозитория
      uses: actions/checkout@v3

    - name: 🐍 Установка Python и зависимостей
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk
        python3 -m pip install --upgrade pip
        pip install buildozer

    - name: 🔧 Сборка Docker образа вручную
      run: |
        git clone https://github.com/kivy/buildozer.git buildozer-docker
        docker build -t my-buildozer buildozer-docker/docker

    - name: ⚙️ Сборка APK через Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/app my-buildozer buildozer android debug

    - name: 📦 Загрузка APK в артефакты
      uses: actions/upload-artifact@v4
      with:
        name: kivyapp-apk
        path: bin/*.apk
