name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
          cd $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          mv cmdline-tools latest
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          buildozer android debug
        env:
          ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-APK
          path: bin/*.apk
