name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK
        run: |
          # Определяем переменную для Android SDK
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          
          # Создаем структуру каталогов для commandline-tools
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          cd $ANDROID_SDK_ROOT/cmdline-tools/latest
          
          # Загружаем архив commandline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          
          # Перемещаем содержимое папки cmdline-tools внутрь каталога latest
          mv cmdline-tools/* .
          rm -rf cmdline-tools
          rm commandlinetools-linux-8512546_latest.zip
          
          # Создаем структуру старой версии инструментов, которую ожидает Buildozer
          mkdir -p $ANDROID_SDK_ROOT/tools/bin
          cp $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager $ANDROID_SDK_ROOT/tools/bin/sdkmanager
          chmod +x $ANDROID_SDK_ROOT/tools/bin/sdkmanager
          
          # Обновляем PATH для доступа к sdkmanager и platform-tools
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools/bin:$PATH
          
          # Принимаем лицензии и устанавливаем необходимые компоненты
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-29" "build-tools;29.0.3" "cmdline-tools;latest"

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          buildozer android debug
        env:
          ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: bin/*.apk
