name: 📱 Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Обновление системы
        run: |
          sudo apt update

      - name: 📦 Установка зависимостей для сборки
        run: |
          sudo apt install -y autoconf automake libtool libtool-bin \
                              build-essential python3-dev \
                              unzip zip libffi-dev libssl-dev \
                              mesa-common-dev mesa-utils \
                              python3-venv python3-pip \
                              openjdk-17-jdk

      - name: 🔥 Установка Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v4

      - name: 📌 Установка pip-зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: ✅ Принятие лицензий Android SDK
        run: |
          yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: 📲 Сборка APK с помощью Buildozer
        run: |
          buildozer android debug

      - name: 📤 Сохранение APK как артефакт
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk
