name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK
        run: |
          # Устанавливаем JAVA_HOME на JDK 8, так как sdkmanager требует именно её
          export JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
          # Определяем переменную для Android SDK
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          
          # Создаем структуру для commandline-tools
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          cd $ANDROID_SDK_ROOT/cmdline-tools/latest
          
          # Загружаем и распаковываем commandline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          
          # Перемещаем содержимое распакованной папки cmdline-tools на уровень выше
          mv cmdline-tools/* .
          rm -rf cmdline-tools
          rm commandlinetools-linux-8512546_latest.zip
          
          # Создаем каталог tools и копируем туда всю структуру из cmdline-tools/latest
          mkdir -p $ANDROID_SDK_ROOT/tools
          cp -r $ANDROID_SDK_ROOT/cmdline-tools/latest/* $ANDROID_SDK_ROOT/tools/
          
          # Обновляем PATH для доступа к sdkmanager и platform-tools
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools/bin:$PATH
          
          # Принимаем лицензии и устанавливаем необходимые компоненты
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-29" "build-tools;29.0.3" "cmdline-tools;latest"

      - name: Build APK
        run: |
          # Используем JDK 8 для сборки
          export JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          buildozer android debug
        env:
          ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: bin/*.apk
