name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python (optional)
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Build APK with Buildozer via Docker
        run: |
          echo "Running Buildozer build using image: homdx/buildozer:latest"
          docker run --rm -v "${{ github.workspace }}":/home/user/hostcwd homdx/buildozer:latest buildozer -v android debug

      - name: List APK output
        run: ls -la bin/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
