name: Build APK with Buildozer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache Buildozer and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.local/share/python-for-android
            ~/.local/bin
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-venv \
                             zip unzip openjdk-17-jdk git \
                             libffi-dev libssl-dev \
                             autoconf automake cmake pkg-config \
                             libltdl-dev

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user --upgrade buildozer cython virtualenv

      - name: Check if python-for-android exists
        run: |
          if [ ! -d "$HOME/.local/share/python-for-android" ]; then
            echo "python-for-android not found, installing..."
            buildozer android clean
          else
            echo "Using cached python-for-android"
          fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BondTrack-APK
          path: bin/*.apk
