name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python (optional)
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Pull Buildozer Docker image
        run: |
          IMAGE_TAG="python3"  # Задаём конкретный тег вместо latest
          echo "Pulling image: kivy/buildozer:${IMAGE_TAG}"
          docker pull kivy/buildozer:${IMAGE_TAG}

      - name: Build APK with Buildozer via Docker
        run: |
          export DOCKER_BUILDKIT=0
          IMAGE_TAG="stable"
          echo "Running Buildozer build using image: kivy/buildozer:${IMAGE_TAG}"
          docker run --rm -v "${{ github.workspace }}":/home/user/hostcwd kivy/buildozer:${IMAGE_TAG} buildozer -v android debug

      - name: List APK output
        run: ls -la bin/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
