name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Build APK with Buildozer via Docker
        run: |
          # Выбираем конкретный тег вместо latest
          IMAGE_TAG="2022.08.01"
          echo "Pulling image: kivy/buildozer:${IMAGE_TAG}"
          docker pull kivy/buildozer:${IMAGE_TAG} || true
          echo "Running Buildozer build..."
          docker run --rm -v "${{ github.workspace }}":/home/user/hostcwd kivy/buildozer:${IMAGE_TAG} buildozer -v android debug

      - name: List output directory
        run: ls -la bin/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
