name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK and NDK
        run: |
          # Используем JDK 8 для совместимости с sdkmanager и python-for-android
          export JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          mkdir -p $ANDROID_SDK_ROOT
          
          # Устанавливаем commandline-tools
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          cd $ANDROID_SDK_ROOT/cmdline-tools/latest
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip
          mv cmdline-tools/* .
          rm -rf cmdline-tools
          rm commandlinetools-linux-8512546_latest.zip
          
          # Копируем инструменты в структуру, которую ожидает buildozer (для корректной работы sdkmanager)
          mkdir -p $ANDROID_SDK_ROOT/tools
          cp -r $ANDROID_SDK_ROOT/cmdline-tools/latest/* $ANDROID_SDK_ROOT/tools/
          
          # Обновляем PATH для доступа к Android SDK
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/tools/bin:$PATH
          
          # Принимаем лицензии и устанавливаем компоненты, включая нужный NDK (версия 21.4.7075529)
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-29" "build-tools;29.0.3" "cmdline-tools;latest" "ndk;21.4.7075529"

      - name: Build APK
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-8-jdk-amd64
          ANDROID_SDK_ROOT: ${{ env.HOME }}/.buildozer/android/platform/android-sdk
          ANDROID_NDK_HOME: ${{ env.HOME }}/.buildozer/android/platform/android-sdk/ndk/21.4.7075529
          ANDROID_NDK: ${{ env.HOME }}/.buildozer/android/platform/android-sdk/ndk/21.4.7075529
          ANDROIDNDK: ${{ env.HOME }}/.buildozer/android/platform/android-sdk/ndk/21.4.7075529
        run: |
          # Сбрасываем переменные, которые могут конфликтовать с нашими настройками
          unset ANDROID_NDK_ROOT
          unset ANDROID_NDK_LATEST_HOME
          unset ANDROIDNDK
          # Задаём нужные переменные для NDK
          export JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.4.7075529
          export ANDROID_NDK=$ANDROID_NDK_HOME
          export ANDROIDNDK=$ANDROID_NDK_HOME
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: bin/*.apk
