on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Скачиваем и устанавливаем libtinfo5 вручную
      - name: Install libtinfo5 manually
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb || true
          sudo apt-get install -f -y

      # Устанавливаем остальные зависимости для сборки
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses6 libncurses-dev libtinfo-dev android-sdk-platform-tools

      # Настройка Java (с обязательным параметром distribution)
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      # Настройка Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      # Сборка APK с помощью Buildozer
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: |
            yes | sdkmanager --licenses
            buildozer -v android debug

      # Загрузка собранных артефактов
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
